apiVersion: apps/v1
kind: Deployment
metadata:
  name: azarch-shopping-cart
spec:
  selector:
    matchLabels:
      app: azarch-shopping-cart
  template:
    metadata:
      labels:
        app: azarch-shopping-cart
    spec:
      containers:
      - name: azarch-shopping-cart
        image: azarchcontainerRegistry.azurecr.io/cart:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
         - containerPort: 80
        env:
            - name: MenusDB
              valueFrom:
                secretKeyRef:
                  name: menudb
                  key: connection-string
            - name: StorageConnectionString
              valueFrom:
                secretKeyRef:
                  name: storageconnectionstring
                  key: connection-string
            - name: Redis
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: connection-string
                
---
apiVersion: v1
kind: Service
metadata:
  name: azarch-shopping-cart
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5004
  selector:
    app: azarch-shopping-cart      
